### ISSUE TITLE
"when is NAME on call" failing with error

### ISSUE THREAD

**Issue by cboscolo** [stripe-contrib/pagerbot#51]
Deployed pagerbot using "Deploy to Heroku" button.

Issuing the following:
`cboscolo [1:03 PM] pagerbot: when is andrew. on call`
Results in:
`pagerbot [1:03 PM] Hmm, that didn't seem to work: undefined method `[]' for nil:NilClass`

Everything else appears to work fine.  For example, if I use the name of the schedule it works:
`cboscolo [1:04 PM] pagerbot: when is andrew on normal`
Results in:
`pagerbot [1:04 PM] Andrew is not scheduled to go on Normal.`

**Comment by macobo** [comment]
Thanks for the report - I'm sadly away from a dev environment for a week, will take a look as soon as I get the opportunity!

In the meantime, PRs are always welcome as well.

**Comment by macobo** [comment]
Sorry about the lack of a fix - I don't have access to a Pagerduty account anymore which means testing and verifying a fix is currently impossible. I've reached out to Pagerduty support, perhaps they'll let me have access to a testing account against which it'd even be possible to write integration tests.

In the meantime, happy to coach someone through solving this bug if there's interest!

**Comment by macobo** [comment]
This is now fixed, thanks! :+1: 

Please let me know if you run into any other issues.

**Comment by cboscolo** [comment]
Thanks for fixing this nil reference issue!  Unfortunately the semantics for use of the keyword `call` still do not work.  I opened separate ticket for this. (#52)  I am sorry I do not have more bandwidth to help you troubleshoot and fix this.
